# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-10.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cscadmin/courses/471_graphics/programs/2015_CmakeCompile/Lab6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cscadmin/courses/471_graphics/programs/2015_CmakeCompile/Lab6

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-10.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-10.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cscadmin/courses/471_graphics/programs/2015_CmakeCompile/Lab6/CMakeFiles /Users/cscadmin/courses/471_graphics/programs/2015_CmakeCompile/Lab6/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cscadmin/courses/471_graphics/programs/2015_CmakeCompile/Lab6/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lab6

# Build rule for target.
Lab6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lab6
.PHONY : Lab6

# fast build rule for target.
Lab6/fast:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/build
.PHONY : Lab6/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f dependencies/glfw/src/CMakeFiles/glfw.dir/build.make dependencies/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

dependencies/glad/src/glad.o: dependencies/glad/src/glad.c.o
.PHONY : dependencies/glad/src/glad.o

# target to build an object file
dependencies/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/dependencies/glad/src/glad.c.o
.PHONY : dependencies/glad/src/glad.c.o

dependencies/glad/src/glad.i: dependencies/glad/src/glad.c.i
.PHONY : dependencies/glad/src/glad.i

# target to preprocess a source file
dependencies/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/dependencies/glad/src/glad.c.i
.PHONY : dependencies/glad/src/glad.c.i

dependencies/glad/src/glad.s: dependencies/glad/src/glad.c.s
.PHONY : dependencies/glad/src/glad.s

# target to generate assembly for a file
dependencies/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/dependencies/glad/src/glad.c.s
.PHONY : dependencies/glad/src/glad.c.s

source/GLSL.o: source/GLSL.cpp.o
.PHONY : source/GLSL.o

# target to build an object file
source/GLSL.cpp.o:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/GLSL.cpp.o
.PHONY : source/GLSL.cpp.o

source/GLSL.i: source/GLSL.cpp.i
.PHONY : source/GLSL.i

# target to preprocess a source file
source/GLSL.cpp.i:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/GLSL.cpp.i
.PHONY : source/GLSL.cpp.i

source/GLSL.s: source/GLSL.cpp.s
.PHONY : source/GLSL.s

# target to generate assembly for a file
source/GLSL.cpp.s:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/GLSL.cpp.s
.PHONY : source/GLSL.cpp.s

source/RenderingHelper.o: source/RenderingHelper.cpp.o
.PHONY : source/RenderingHelper.o

# target to build an object file
source/RenderingHelper.cpp.o:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/RenderingHelper.cpp.o
.PHONY : source/RenderingHelper.cpp.o

source/RenderingHelper.i: source/RenderingHelper.cpp.i
.PHONY : source/RenderingHelper.i

# target to preprocess a source file
source/RenderingHelper.cpp.i:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/RenderingHelper.cpp.i
.PHONY : source/RenderingHelper.cpp.i

source/RenderingHelper.s: source/RenderingHelper.cpp.s
.PHONY : source/RenderingHelper.s

# target to generate assembly for a file
source/RenderingHelper.cpp.s:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/RenderingHelper.cpp.s
.PHONY : source/RenderingHelper.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/tiny_obj_loader.o: source/tiny_obj_loader.cc.o
.PHONY : source/tiny_obj_loader.o

# target to build an object file
source/tiny_obj_loader.cc.o:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/tiny_obj_loader.cc.o
.PHONY : source/tiny_obj_loader.cc.o

source/tiny_obj_loader.i: source/tiny_obj_loader.cc.i
.PHONY : source/tiny_obj_loader.i

# target to preprocess a source file
source/tiny_obj_loader.cc.i:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/tiny_obj_loader.cc.i
.PHONY : source/tiny_obj_loader.cc.i

source/tiny_obj_loader.s: source/tiny_obj_loader.cc.s
.PHONY : source/tiny_obj_loader.s

# target to generate assembly for a file
source/tiny_obj_loader.cc.s:
	$(MAKE) -f CMakeFiles/Lab6.dir/build.make CMakeFiles/Lab6.dir/source/tiny_obj_loader.cc.s
.PHONY : source/tiny_obj_loader.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Lab6"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glfw"
	@echo "... dependencies/glad/src/glad.o"
	@echo "... dependencies/glad/src/glad.i"
	@echo "... dependencies/glad/src/glad.s"
	@echo "... source/GLSL.o"
	@echo "... source/GLSL.i"
	@echo "... source/GLSL.s"
	@echo "... source/RenderingHelper.o"
	@echo "... source/RenderingHelper.i"
	@echo "... source/RenderingHelper.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/tiny_obj_loader.o"
	@echo "... source/tiny_obj_loader.i"
	@echo "... source/tiny_obj_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

